Models/Author.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SqlServerWebDemo.Models
{
    public class Author
    {
        public int AuthorId { get; set; }
        
        [Required]
        public string FirstName { get; set; }
        
        [Required]
        public string LastName { get; set; }
        
        public ICollection<Book> Books { get; set; } = new List<Book>();
    }
}

Models/Book.cs
using System.ComponentModel.DataAnnotations;

namespace SqlServerWebDemo.Models
{
    public class Book
    {
        public int BookId { get; set; }
        
        [Required]
        public string Title { get; set; }
        
        [Required]
        public int AuthorId { get; set; }
        
        public Author Author { get; set; }
    }
}

Models/DemoContext.cs
using Microsoft.EntityFrameworkCore;

namespace SqlServerWebDemo.Models
{
    public class DemoContext : DbContext
    {
        public DemoContext(DbContextOptions options) : base(options) {}

        public DbSet<Book> Books { get; set; }
        public DbSet<Author> Authors { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace SqlServerWebDemo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ViewModels/Home/CloudFoundryViewModel.cs
using Steeltoe.Extensions.Configuration.CloudFoundry;


namespace SqlServerWebDemo.ViewModels.Home
{
    public class CloudFoundryViewModel
    {
        public CloudFoundryViewModel(CloudFoundryApplicationOptions appOptions, CloudFoundryServicesOptions serviceOptions)
        {
            CloudFoundryServices = serviceOptions;
            CloudFoundryApplication = appOptions;
        }
        public CloudFoundryServicesOptions CloudFoundryServices { get;}
        public CloudFoundryApplicationOptions CloudFoundryApplication { get;}
    }
}

Controllers/AuthorController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SqlServerWebDemo.Models;

namespace SqlServerWebDemo.Controllers
{
    public class AuthorController : Controller
    {
        private DemoContext _context;

        public AuthorController(DemoContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("FirstName, LastName")] Author author)
        {
            _context.Add(author);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var author = await _context.Authors.FindAsync(id);
            _context.Authors.Remove(author);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/BookController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SqlServerWebDemo.Models;

namespace SqlServerWebDemo.Controllers
{
    public class BookController : Controller
    {
        private DemoContext _context;

        public BookController(DemoContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var authors = await _context.Authors.Select(a => new SelectListItem
            {
                Value = a.AuthorId.ToString(),
                Text = $"{a.FirstName} {a.LastName}"
            }).ToListAsync();
            ViewBag.Authors = authors.OrderBy(o => o.Text);

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Title, AuthorId")] Book book)
        {
            _context.Books.Add(book);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var book = await _context.Books.FindAsync(id);
            _context.Books.Remove(book);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/HomeController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using SqlServerWebDemo.Models;
using SqlServerWebDemo.ViewModels.Home;
using Steeltoe.Extensions.Configuration.CloudFoundry;

namespace SqlServerWebDemo.Controllers
{
    public class HomeController : Controller
    {
        private CloudFoundryServicesOptions CloudFoundryServices { get; set; }
        private CloudFoundryApplicationOptions CloudFoundryApplication { get; set; }

        private DemoContext _context;

        public HomeController(
            IOptions<CloudFoundryApplicationOptions> appOptions,
            IOptions<CloudFoundryServicesOptions> serviceOptions,
            DemoContext context)
        {
            CloudFoundryServices = serviceOptions.Value;
            CloudFoundryApplication = appOptions.Value;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _context.Authors.Include(a => a.Books).AsNoTracking().ToListAsync();
            return View(model);
        }

        public IActionResult CloudFoundry()
        {
            return View(new CloudFoundryViewModel(
                CloudFoundryApplication ?? new CloudFoundryApplicationOptions(),
                CloudFoundryServices ?? new CloudFoundryServicesOptions()));
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Views/Author/Create.cshtml
@model Author
@{
    ViewBag.Title = "New Author";
}
<h1>@ViewBag.Title</h1>
@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(model => model.FirstName)
        @Html.TextBoxFor(model => model.FirstName, new {@class = "form-control"})
        @Html.ValidationMessageFor(model => model.FirstName, "", new {@class = "text-danger"})
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.LastName)
        @Html.TextBoxFor(model => model.LastName, new {@class = "form-control"})
        @Html.ValidationMessageFor(model => model.LastName, "", new {@class = "text-danger"})
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
}
@section Scripts {
    <partial name="_ValidationScriptsPartial"/>
}

Views/Book/Create.cshtml
@model Book
@{
    ViewBag.Title = "New Book";
}
<h1>@ViewBag.Title</h1>
@using(Html.BeginForm()){
    <div class="form-group">
        @Html.LabelFor(model => model.AuthorId)
        @Html.DropDownListFor(model => model.AuthorId, (IEnumerable<SelectListItem>)ViewBag.Authors, string.Empty, new { @class="form-control"}) 
        @Html.ValidationMessageFor(model => model.AuthorId, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Title)
        @Html.TextBoxFor(model => model.Title, new { @class="form-control"})
        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
}
@section Scripts {
    <partial name="_ValidationScriptsPartial"/>
}

Views/Home/CloudFoundry.cshtml
@model CloudFoundryViewModel
@{
    ViewData["Title"] = "CloudFoundry Configuration";
}

<h2>@ViewData["Title"]</h2>
<h3>VCAP_APPLICATION</h3>

<h4>vcap:application:application_name = @Model.CloudFoundryApplication.ApplicationName</h4>
<h4>vcap:application:application_id = @Model.CloudFoundryApplication.ApplicationId</h4>
<h4>vcap:application:application_version = @Model.CloudFoundryApplication.ApplicationVersion</h4>
<h4>vcap:application:application_uris = @(Model.CloudFoundryApplication.ApplicationUris != null ? Model.CloudFoundryApplication.ApplicationUris[0] : "")</h4>

<h4>vcap:application:space_name = @Model.CloudFoundryApplication.SpaceName</h4>
<h4>vcap:application:space_id = @Model.CloudFoundryApplication.SpaceId</h4>

<h4>vcap:application:instance_id = @Model.CloudFoundryApplication.InstanceId</h4>
<h4>vcap:application:instance_index = @Model.CloudFoundryApplication.InstanceIndex</h4>

<h4>vcap:application:limits:disk = @Model.CloudFoundryApplication.DiskLimit</h4>
<h4>vcap:application:limits:mem = @Model.CloudFoundryApplication.MemoryLimit</h4>
<h4>vcap:application:limits:fds = @Model.CloudFoundryApplication.FileDescriptorLimit</h4>

<h4>vcap:application:start = @Model.CloudFoundryApplication.Start</h4>

<h3>VCAP_SERVICES</h3>

@foreach (var service in Model.CloudFoundryServices.ServicesList)
{
    <h4>vcap:services:@(service.Label):label = @service.Label</h4>
    <h4>vcap:services:@(service.Label):plan = @service.Plan</h4>
    <h4>vcap:services:@(service.Label):name = @service.Name</h4>
    <h4>vcap:services:@(service.Label):tags = @foreach (var tag in service.Tags) { @(tag + " ") }</h4>
    <h4>vcap:services:@(service.Label):credentials =</h4>
    <service-credentials credentials="@service.Credentials"></service-credentials>
}

Views/Home/Index.cshtml
@model IEnumerable<SqlServerWebDemo.Models.Author>
@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<div class="container">
    <h1 class="display-4">Books by Author</h1>
    @if (Model.Any())
    {
        <ul>
            @foreach (var author in Model.OrderBy(o => o.FirstName))
            {
                <li><h2>@author.FirstName @author.LastName<span class="float-right">@Html.ActionLink("Delete", "Delete", "Author", new { id = author.AuthorId })</span></h2>
                    <ul class="list-group">
                        @foreach (var book in author.Books.OrderBy(o => o.Title))
                        {
                            <li class="list-group-item">@book.Title<span class="float-right">@Html.ActionLink("Delete", "Delete", "Book", new { id = book.BookId })</span></li>
                        }
                    </ul>
                </li>
            }
        </ul>
        <div>@Html.ActionLink("New Author", "create", "Author")</div>
        <div>@Html.ActionLink("New Book", "create", "Book")</div>
    }
    else
    {
        <div>@Html.ActionLink("New Author", "create", "Author")</div>
    }
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @* For some reason, Chrome tries to translate the CloudFoundry settings page into Portuguese... *@
    <meta name="google" content="notranslate">
    <title>@ViewData["Title"] - SQL Server Web Demo</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="CloudFoundry">Cloud Foundry Config</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - HSDP
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>